### ISSUE TITLE
您好，请问您这个算法论文的源代码是在哪找的？

### ISSUE THREAD

**Issue by cadxy** [gpx333/Graduation_project#2]
你好，我想复现一下您的源代码。但是我下载之后感觉里面的的内容有点多，请问复现的时候大致步骤是什么呢？能大概说一下吗？我把数据集下载后我看代码里面要求的是一个txt文件，但是下载的数据集是图片，应该怎么做呢？
另外，您这个算法参考论文（Deep Multi-Task Augmented Feature Learning via Hierarchical Graph Neural Network）的源代码有吗？我在github上没找到，请问您是在哪找的？
非常希望您能回答一下我的问题，十分感谢！

**Comment by Pengxin-Guo** [comment]
这个网站的话是用django框架写的，所以看着会有点复杂，但里面的内容并不多的，你可以大致了解一下怎么用django框架搭建网站，然后应该就能看懂我这个代码了，如果到时候还有什么问题的话，也可以给我留言。
至于这个参考论文的源代码，你可以留个email，我发给你，供你参考。

**Comment by cadxy** [comment]
您好，非常感谢您回答我的疑问，我的邮箱是1639375966@qq.com,希望您能把参考论文的源码分享一下，非常感谢您

**Comment by Pengxin-Guo** [comment]
已发送，请注意查收。

**Comment by cadxy** [comment]
好的，已收到，非常感谢您，祝您生活愉快

**Comment by my-my157** [comment]
您好，本人小白一个，想复现一下您的源代码，但是不会把图片变为txt文件输入。请问可以将源代码发给我一份吗，我的邮箱是1340816837@qq.com,非常感谢

**Comment by Pengxin-Guo** [comment]
这个就是用VGG或者ResNet提取的特征，将这些特征存到txt里面就行。
