### ISSUE TITLE
您好，请问论文源代码里面的数据格式是怎么样的

### ISSUE THREAD

**Issue by cadxy** [gpx333/Graduation_project#3]
您好，我们下载了论文源代码里面的数据，并阅读了一下代码。源代码给出的数据是txt文档格式的，里面的每一行代表了一个数据，请问您知道每一行的数据是几维或者说有什么格式特征吗？我们尝试自己在每一行里写下我们自己的一个数据，然后运行代码的时候报错，错误是‘tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 96 of dimension 0 out of bounds.for 'strided_slice_2748' (op: 'StridedSlice') with input shapes: [96,8], [1], [1], [1] and with computed input tensors: input[1] = <96>, input[2] = <97>, input[3] = <1>.’
请问这种问题该怎么解决您有思路吗？十分感谢

**Comment by cadxy** [comment]
您好，经过我们的分析我们发现这个错误是因为我们的任务数设置的高了。假如说我们设置了10个任务那么就会报这个错。请问如果自己想设置的任务多一些的话需要修改一下哪一块关键的代码呢？

**Comment by Pengxin-Guo** [comment]
不好意思，这个我也太久没看了，你们可以仔细找一下。

**Comment by ReeceChang0912** [comment]
hello 同学你好 我发现你的那个glf 带宽超额了  我clone不了那个,npy的文件   可以麻烦你搞一下吗？  
或者就是你的数据集是怎么转换成.txt文件的呀  能分享一下那个txt文件吗？

**Comment by Pengxin-Guo** [comment]
我不太确定你说的npy文件是vgg19的npy嘛，如果是的话你可以去找预训练的vgg19的模型，我们就是用这个提取的特征。
对于数据集是如何转化成txt文件的，就是将原始的图像输入到预训练的vgg19网络（将vgg19的最后一层分类头去掉），然后把抽出来的特征存入txt文件就行。

**Comment by ReeceChang0912** [comment]
十分感谢 我大概理解数据集是怎么转化为txt的了  
我说的.npy文件是参数Parameters里文件夹那里的那四个.npy

**Comment by Pengxin-Guo** [comment]
噢，那些npy文件是我们训练好我们的模型之后保存下来的参数，只是分开保存下来了而已，你也可以用提供的数据集重新训练一下这个模型。
如果你确实需要这些npy文件的话可以留个邮箱，我通过邮箱发给你。

**Comment by ReeceChang0912** [comment]
嗯嗯  太感谢您了  我的邮箱是1584539345@qq.com  祝您多发顶会顶刊 哈哈

**Comment by Pengxin-Guo** [comment]
哈哈 谢谢你 你也是哈

**Comment by 469555417** [comment]
你好  请问numpy版本是多少呢？我报错”Object arrays cannot be loaded when allow_pickle=False”查了下说可能是numpy版本过高

**Comment by 469555417** [comment]
请问python版本是3.6吗  django版本是3.0吗

> npy

可以给我也发一份吗 469555417@qq.com 谢谢你

**Comment by Pengxin-Guo** [comment]
python版本应该是比较低的3.几的版本，因为是2年前的项目了，具体我也记不清楚了。django版本我也记不得了。
npy文件我下载下来也是有问题的，也需要解决lfs的问题，和上面那个朋友遇到的问题一样。原始的npy文件我也没有备份了，不好意思。

**Comment by 469555417** [comment]
谢谢谢谢，感谢同学，我就想看看代码跑出来的结果是什么样的。因为我是初学者，刚接触图像分类还在摸索，我试了python3.6，django3.0可以跑代码但是有错误，后面才发现那个错误应该是.npy文件的问题，然后下载不下来因为github的lfs容量小的问题。看来还是得从头认认真真学才行。再次感谢你。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pengxin ***@***.***&gt;; 
发送时间: 2022年5月23日(星期一) 晚上9:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gpx333/Graduation_project] 您好，请问论文源代码里面的数据格式是怎么样的 (#3)





 
python版本应该是比较低的3.几的版本，因为是2年前的项目了，具体我也记不清楚了。django版本我也记不得了。
 npy文件我下载下来也是有问题的，也需要解决lfs的问题，和上面那个朋友遇到的问题一样。原始的npy文件我也没有备份了，不好意思。
